---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver:
    box: ubuntu/trusty64
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver:
    box: ubuntu/precise64
  run_list:
  - recipe[apt]
  - recipe[build-essential]

suites:
- name: install
  run_list:
  - recipe[test::install]
