name             'overwatch'
maintainer       'trott'
maintainer_email 'trott@citrusbyte.com'
license          'Apache 2.0'
description      'Installs/Configures overwatch'
long_description 'Installs/Configures overwatch'
version          '0.1.0'
